// Generated by gencpp from file asctec_msgs/GPSData.msg
// DO NOT EDIT!


#ifndef ASCTEC_MSGS_MESSAGE_GPSDATA_H
#define ASCTEC_MSGS_MESSAGE_GPSDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace asctec_msgs
{
template <class ContainerAllocator>
struct GPSData_
{
  typedef GPSData_<ContainerAllocator> Type;

  GPSData_()
    : header()
    , latitude(0)
    , longitude(0)
    , height(0)
    , speed_x(0)
    , speed_y(0)
    , heading(0)
    , horizontal_accuracy(0)
    , vertical_accuracy(0)
    , speed_accuracy(0)
    , numSV(0)
    , status(0)  {
    }
  GPSData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , latitude(0)
    , longitude(0)
    , height(0)
    , speed_x(0)
    , speed_y(0)
    , heading(0)
    , horizontal_accuracy(0)
    , vertical_accuracy(0)
    , speed_accuracy(0)
    , numSV(0)
    , status(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _latitude_type;
  _latitude_type latitude;

   typedef int32_t _longitude_type;
  _longitude_type longitude;

   typedef int32_t _height_type;
  _height_type height;

   typedef int32_t _speed_x_type;
  _speed_x_type speed_x;

   typedef int32_t _speed_y_type;
  _speed_y_type speed_y;

   typedef int32_t _heading_type;
  _heading_type heading;

   typedef int32_t _horizontal_accuracy_type;
  _horizontal_accuracy_type horizontal_accuracy;

   typedef int32_t _vertical_accuracy_type;
  _vertical_accuracy_type vertical_accuracy;

   typedef int32_t _speed_accuracy_type;
  _speed_accuracy_type speed_accuracy;

   typedef int32_t _numSV_type;
  _numSV_type numSV;

   typedef int32_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::asctec_msgs::GPSData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asctec_msgs::GPSData_<ContainerAllocator> const> ConstPtr;

}; // struct GPSData_

typedef ::asctec_msgs::GPSData_<std::allocator<void> > GPSData;

typedef boost::shared_ptr< ::asctec_msgs::GPSData > GPSDataPtr;
typedef boost::shared_ptr< ::asctec_msgs::GPSData const> GPSDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asctec_msgs::GPSData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asctec_msgs::GPSData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace asctec_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'asctec_msgs': ['/home/asctec/catkin_ws/src/asctec_drivers/asctec_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::asctec_msgs::GPSData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asctec_msgs::GPSData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asctec_msgs::GPSData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asctec_msgs::GPSData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asctec_msgs::GPSData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asctec_msgs::GPSData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asctec_msgs::GPSData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b71de9435ba6759a86f427d436c58ccb";
  }

  static const char* value(const ::asctec_msgs::GPSData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb71de9435ba6759aULL;
  static const uint64_t static_value2 = 0x86f427d436c58ccbULL;
};

template<class ContainerAllocator>
struct DataType< ::asctec_msgs::GPSData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asctec_msgs/GPSData";
  }

  static const char* value(const ::asctec_msgs::GPSData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asctec_msgs::GPSData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Software License Agreement (BSD License)\n\
#\n\
# Copyright (c) 2010\n\
#  William Morris <morris@ee.ccny.cuny.edu>\n\
#  Ivan Dryanovski <ivan.dryanovski@gmail.com>\n\
# All rights reserved.\n\
#\n\
# Redistribution and use in source and binary forms, with or without\n\
# modification, are permitted provided that the following conditions\n\
# are met:\n\
#\n\
#  * Redistributions of source code must retain the above copyright\n\
#    notice, this list of conditions and the following disclaimer.\n\
#  * Redistributions in binary form must reproduce the above\n\
#    copyright notice, this list of conditions and the following\n\
#    disclaimer in the documentation and/or other materials provided\n\
#    with the distribution.\n\
#  * Neither the name of CCNY Robotics Lab nor the names of its\n\
#    contributors may be used to endorse or promote products derived\n\
#    from this software without specific prior written permission.\n\
#\n\
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n\
# \"AS IS\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n\
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS\n\
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE\n\
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,\n\
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,\n\
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;\n\
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n\
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT\n\
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN\n\
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE\n\
# POSSIBILITY OF SUCH DAMAGE.\n\
\n\
Header header\n\
# latitude/longitude in deg * 10^7\n\
int32 latitude\n\
int32 longitude\n\
\n\
#GPS height in mm\n\
int32 height\n\
\n\
#speed in x (E/W) and y(N/S) in mm/s\n\
int32 speed_x\n\
int32 speed_y\n\
\n\
#GPS heading in deg * 100\n\
int32 heading\n\
\n\
#accuracy estimates in mm and mm/s\n\
int32 horizontal_accuracy\n\
int32 vertical_accuracy\n\
int32 speed_accuracy\n\
\n\
#number of satellite vehicles used in NAV solution\n\
int32 numSV\n\
\n\
#GPS status information; 0x03 = valid GPS fix\n\
int32 status\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::asctec_msgs::GPSData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asctec_msgs::GPSData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.height);
      stream.next(m.speed_x);
      stream.next(m.speed_y);
      stream.next(m.heading);
      stream.next(m.horizontal_accuracy);
      stream.next(m.vertical_accuracy);
      stream.next(m.speed_accuracy);
      stream.next(m.numSV);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GPSData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asctec_msgs::GPSData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asctec_msgs::GPSData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "latitude: ";
    Printer<int32_t>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<int32_t>::stream(s, indent + "  ", v.longitude);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    s << indent << "speed_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed_x);
    s << indent << "speed_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed_y);
    s << indent << "heading: ";
    Printer<int32_t>::stream(s, indent + "  ", v.heading);
    s << indent << "horizontal_accuracy: ";
    Printer<int32_t>::stream(s, indent + "  ", v.horizontal_accuracy);
    s << indent << "vertical_accuracy: ";
    Printer<int32_t>::stream(s, indent + "  ", v.vertical_accuracy);
    s << indent << "speed_accuracy: ";
    Printer<int32_t>::stream(s, indent + "  ", v.speed_accuracy);
    s << indent << "numSV: ";
    Printer<int32_t>::stream(s, indent + "  ", v.numSV);
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASCTEC_MSGS_MESSAGE_GPSDATA_H
